export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_SAMPLES = 'CLEAR_SAMPLES';
export const INJECT_SAMPLES = 'INJECT_SAMPLES';
export const REQUEST_SAMPLES = 'REQUEST_SAMPLES';
export const REFRESH_SAMPLES = 'REFRESH_SAMPLES';
export const TIMEOUT_SAMPLES = 'TIMEOUT_SAMPLES';
